### ISSUE TITLE
Проблема с кириллицей 

### ISSUE THREAD

**Issue by kirich1368** [FRedEnergy/q-report#8]
Здравствуйте! У  меня одного так с кириллицей?
![default](https://cloud.githubusercontent.com/assets/18468664/17603555/5fd95a6e-601a-11e6-89d3-c2e44bd111ad.png)

**Comment by abvadabra** [comment]
Решено добавлением следующих параметров к ссылке на базу данных:
`?useUnicode=true&characterEncoding=utf8`

**Comment by ghost** [comment]
Спасибо
